### PR TITLE
Support extracting content based on tags as well as line numbers.

### PR DESCRIPTION
**Pull request by robertwb**

### CODE REVIEW

**Comment by bwillis** [comment]
Interesting request, do you have an example of your use case that I can check out?

**Comment by robertwb** [comment]
The main motivation is to have *tested* snippets of code in our documentation. E.g.

https://github.com/apache/beam/blob/python-sdk/sdks/python/apache_beam/examples/snippets/snippets_test.py

to build

https://beam.apache.org/documentation/programming-guide/#transforms-flatten-partition

using jekyll. Line numbers will be difficult to keep in sync as the code and documentation (particularly earlier examples) evolve.

**Comment by robertwb** [comment]
Any more thoughts on this? I'd like to start using it.

**Comment by bwillis** [comment]
Thanks for providing a use case, I think that's a great idea. Sorry for the delay!

**Comment by robertwb** [comment]
Thanks! I assume you'll be re-publishing this gem as well, right?

**Comment by bwillis** [comment]
Should be up now, lemme know if you have any issues!

**Pull request merged**
